server.port=8090

#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-market
spring.datasource.username=postgres
spring.datasource.password=

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER